aliases:
  - &2023 "2023.2.17f1"

env:
    UNITY_VERSION: *2023
    XCODE_VERSION: "15.3.0"

agents:
  queue: "macos-14"

steps:
  - label: Build Unity 2023 MacOS and WebGL test fixtures
    timeout_in_minutes: 30
    key: "cocoa-webgl-2023-fixtures"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: *2023
      # Python2 needed for WebGL to build
#      EMSDK_PYTHON: "/Library/Frameworks/Python.framework/Versions/2.7/bin/python"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
    commands:
      - scripts/ci-build-macos-packages.sh
    artifact_paths:
      - unity.log
      - features/fixtures/maze_runner/build/MacOS-2023.2.17f1.zip
      - features/fixtures/maze_runner/build/WebGL-2023.2.17f1.zip
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run macOS desktop tests
  #
  - label: Run MacOS e2e tests for Unity 2023
    timeout_in_minutes: 60
    depends_on: "cocoa-webgl-2023-fixtures"
    env:
      UNITY_VERSION: *2023
    plugins:
      artifacts#v1.5.0:
        download:
          - features/fixtures/maze_runner/build/MacOS-2023.2.17f1.zip
        upload:
          - maze_output/**/*
          - '*-mazerunner.log'
          - maze_output/metrics.csv
    commands:
      - scripts/ci-run-macos-tests-csharp.sh

  - label: Run WebGL e2e tests for Unity 2023
    timeout_in_minutes: 30
    depends_on: "cocoa-webgl-2023-fixtures"
    env:
      UNITY_VERSION: *2023
    plugins:
      artifacts#v1.5.0:
        download:
          - features/fixtures/maze_runner/build/WebGL-2023.2.17f1.zip
        upload:
          - maze_output/**/*
          - maze_output/metrics.csv
    # TODO: WebGL persistence tests are currently skipped pending PLAT-8151
    commands:
      - scripts/ci-run-webgl-tests.sh
