steps:

  #
  # Build Windows test fixture
  #
  - label: Build Unity 2020 Windows test fixture
    timeout_in_minutes: 30
    key: 'windows-2020-fixture'
    agents:
      queue: macos-12-arm
    plugins:
      artifacts#v1.5.0:
        upload:
          - features/fixtures/maze_runner/build/Windows-2020.3.32f1.zip
    commands:
      - mkdir -p features/fixtures/maze_runner/build
      - cp Windows-2020.3.32f1.zip features/fixtures/maze_runner/build/Windows-2020.3.32f1.zip

  #
  # Run Windows e2e tests
  #
  - label: Run Windows e2e tests for Unity 2020
    timeout_in_minutes: 30
    depends_on: 'windows-2020-fixture'
    agents:
      queue: steve-laptop
    env:
      UNITY_VERSION: "2020.3.32f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - features/fixtures/maze_runner/build/Windows-2020.3.32f1.zip
    command:
      - scripts/ci-run-windows-tests-wsl.sh
    retry:
      manual:
        permit_on_passed: true
