agents:
  queue: macos-12-arm-unity

steps:

  #
  # Build Android test fixtures
  #
  - label: ':android: Build Android test fixture for Unity 2018'
    timeout_in_minutes: 30
    key: 'build-android-fixture-2018'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2018.4.36f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk
          - features/fixtures/unity.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':android: Build Android test fixture for Unity 2019'
    timeout_in_minutes: 30
    key: 'build-android-fixture-2019'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2019.4.35f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk
          - features/fixtures/unity.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':android: Build Android test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: 'build-android-fixture-2021'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2021.2.17f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2021.2.17f1.apk
          - features/fixtures/unity.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':android: Build Android EDM test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: 'build-edm-fixture-2021'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2021.2.17f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/EDM_Fixture/edm_2021.2.17f1.apk
          - features/scripts/mobile/buildEdmFixture.log
          - features/scripts/mobile/edmImport.log
          - features/scripts/mobile/enableEdm.log
    commands:
      - rake test:edm:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run Android tests
  #
  - label: ':android: Run Android e2e tests for Unity 2018'
    timeout_in_minutes: 30
    depends_on: 'build-android-fixture-2018'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/android"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  - label: ':android: Run Android e2e tests for Unity 2019'
    timeout_in_minutes: 30
    depends_on: 'build-android-fixture-2019'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/android"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  # TODO: PLAT-7967 Investigate failures specific to Unity 2021 on Android
  - label: ':android: Run Android e2e tests for Unity 2021'
    timeout_in_minutes: 30
    skip: Pending PLAT-7967
    depends_on: 'build-android-fixture-2021'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2021.2.17f1.apk"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2021.2.17f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/android"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  - label: ':android: Run Android EDM e2e tests for Unity 2021'
    timeout_in_minutes: 30
    depends_on: 'build-edm-fixture-2021'
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2021.2.17f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/EDM_Fixture/edm_2021.2.17f1.apk"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/EDM_Fixture/edm_2021.2.17f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/edm"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  #
  # Build iOS test fixtures
  #
  - label: ':ios: Generate Xcode project - Unity 2018'
    timeout_in_minutes: 30
    key: 'generate-fixture-project-2018'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2018.4.36f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/unity.log
          - project_2018.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2018.tgz  features/fixtures/maze_runner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2018'
    timeout_in_minutes: 30
    key: 'build-ios-fixture-2018'
    depends_on: 'generate-fixture-project-2018'
    agents:
      queue: macos-12-arm-unity
    env:
      UNITY_VERSION: "2018.4.36f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
          - project_2018.tgz
        upload:
          - features/fixtures/maze_runner/mazerunner_2018.4.36f1.ipa
          - features/fixtures/unity.log
    commands:
      - tar -zxf project_2018.tgz features/fixtures/maze_runner
      - rake test:ios:build_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Generate Xcode project - Unity 2019'
    timeout_in_minutes: 30
    key: 'generate-fixture-project-2019'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2019.4.35f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/unity.log
          - project_2019.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2019.tgz features/fixtures/maze_runner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2019'
    timeout_in_minutes: 30
    key: 'build-ios-fixture-2019'
    depends_on: 'generate-fixture-project-2019'
    agents:
      queue: macos-12-arm-unity
    env:
      UNITY_VERSION: "2019.4.35f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
          - project_2019.tgz
        upload:
          - features/fixtures/maze_runner/mazerunner_2019.4.35f1.ipa
          - features/fixtures/unity.log
    commands:
      - tar -zxf project_2019.tgz features/fixtures/maze_runner
      - rake test:ios:build_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Generate Xcode project - Unity 2021'
    timeout_in_minutes: 30
    key: 'generate-fixture-project-2021'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2021.2.17f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/unity.log
          - project_2021.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2021.tgz features/fixtures/maze_runner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2021'
    timeout_in_minutes: 30
    key: 'build-ios-fixture-2021'
    depends_on: 'generate-fixture-project-2021'
    agents:
      queue: macos-12-arm-unity
    env:
      UNITY_VERSION: "2021.2.17f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
          - project_2021.tgz
        upload:
          - features/fixtures/maze_runner/mazerunner_2021.2.17f1.ipa
          - features/fixtures/unity.log
    commands:
      - tar -zxf project_2021.tgz features/fixtures/maze_runner
      - rake test:ios:build_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run iOS tests
  #
  - label: ':ios: Run iOS e2e tests for Unity 2018'
    timeout_in_minutes: 30
    depends_on: 'build-ios-fixture-2018'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2018.4.36f1.ipa"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2018.4.36f1.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--fail-fast"
          - "features/ios"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  - label: ':ios: Run iOS e2e tests for Unity 2019'
    timeout_in_minutes: 30
    depends_on: 'build-ios-fixture-2019'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2019.4.35f1.ipa"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2019.4.35f1.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--fail-fast"
          - "features/ios"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  - label: ':ios: Run iOS e2e tests for Unity 2021'
    timeout_in_minutes: 30
    depends_on: 'build-ios-fixture-2021'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2021.2.17f1.ipa"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2021.2.17f1.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--fail-fast"
          - "features/ios"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager
