agents:
  queue: macos-12-arm-unity

steps:

  #
  # Build notifier.  We run tests for all Unity versions with the 2018 artifacts, as that is what we ship.
  #
  - label: Build notifier artifacts
    timeout_in_minutes: 30
    key: 'build-artifacts'
    env:
      UNITY_VERSION: "2018.4.36f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Build Android test fixtures
  #
  - label: ':android: Build Android test fixture for Unity 2020'
    timeout_in_minutes: 30
    key: 'build-android-fixture-2020'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk
          - features/fixtures/unity.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run Android tests
  #
  - label: ':android: Run Android e2e tests for Unity 2020'
    timeout_in_minutes: 30
    depends_on: 'build-android-fixture-2020'
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk"
          - "--farm=bs"
          - "--device=ANDROID_9_0"
          - "features/android"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager


  #
  # Build iOS test fixtures
  #
  - label: ':ios: Generate Xcode project - Unity 2020'
    timeout_in_minutes: 30
    key: 'generate-fixture-project-2020'
    depends_on: 'build-artifacts'
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/unity.log
          - project_2020.tgz
    commands:
      - rake test:ios:generate_xcode
      - tar -zvcf project_2020.tgz features/fixtures/maze_runner/mazerunner_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ':ios: Build iOS test fixture for Unity 2020'
    timeout_in_minutes: 30
    key: 'build-ios-fixture-2020'
    depends_on: 'generate-fixture-project-2020'
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
          - project_2020.tgz
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.48f1.ipa
          - features/fixtures/unity.log
    commands:
      - tar -zxf project_2020.tgz features/fixtures/maze_runner
      - rake test:ios:build_xcode
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run iOS tests
  #
  - label: ':ios: Run iOS e2e tests for Unity 2020'
    timeout_in_minutes: 30
    depends_on: 'build-ios-fixture-2020'
    agents:
      queue: opensource
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.3.48f1.ipa"
        upload:
          - "maze_output/**/*"
      docker-compose#v3.7.0:
        pull: maze-runner
        run: maze-runner
        command:
          - "--app=/app/features/fixtures/maze_runner/mazerunner_2020.3.48f1.ipa"
          - "--farm=bs"
          - "--device=IOS_14"
          - "--fail-fast"
          - "features/ios"
    concurrency: 9
    concurrency_group: browserstack-app
    concurrency_method: eager

  #
  # Conditionally trigger full pipeline
  #
  - label: 'Conditionally trigger full set of tests'
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
