agents:
  queue: macos-12-arm-unity

steps:

  #
  # Build Android test fixtures
  #
  - label: ":android: Build Android test fixture for Unity 2018"
    timeout_in_minutes: 30
    key: "build-android-fixture-2018"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: "2018.4.36f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk
          - features/fixtures/build_android_apk.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android test fixture for Unity 2019"
    timeout_in_minutes: 30
    key: "build-android-fixture-2019"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: "2019.4.35f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk
          - features/fixtures/build_android_apk.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android test fixture for Unity 2021"
    timeout_in_minutes: 30
    key: "build-android-fixture-2021"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: "2021.3.27f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2021.3.27f1.apk
          - features/fixtures/build_android_apk.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":android: Build Android test fixture for Unity 2022"
    timeout_in_minutes: 30
    key: "build-android-fixture-2022"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: "2022.3.2f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2022.3.2f1.apk
          - features/fixtures/build_android_apk.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run Android tests
  #
  - label: ":bitbar: :android: Run Android e2e tests for Unity 2018"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2018"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2018.4.36f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2018.4.36f1.apk"
          - "--farm=bb"
          - "--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android e2e tests for Unity 2019"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2019"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2019.4.35f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2019.4.35f1.apk"
          - "--farm=bb"
          - "--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android e2e tests for Unity 2021"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2021"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2021.3.27f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2021.3.27f1.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2021.3.27f1.apk"
          - "--farm=bb"
          - "--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  - label: ":bitbar: :android: Run Android e2e tests for Unity 2022"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2022"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2022.3.2f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2022.3.2f1.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2022.3.2f1.apk"
          - "--farm=bb"
          - "--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

