agents:
  queue: macos-12-arm-unity

steps:

  #
  # Build Windows test fixture
  #
  - label: Build Unity 2020 Windows test fixture
    timeout_in_minutes: 30
    key: 'windows-2020-fixture'
    agents:
      queue: win-general-1
    env:
      UNITY_VERSION: "2020.3.32f1"
    commands:
      - cd features/scripts
      - ./build_maze_runner.sh windows
      - cd ../../fixtures/maze_runner/build
      - zip -r Windows-$UNITY_VERSION.zip Windows
    artifact_paths:
      - unity.log
      - features/fixtures/maze_runner/build/Windows-2020.3.32f1.zip
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run Windows e2e tests
  #
  - label: Run Windows e2e tests for Unity 2020
    timeout_in_minutes: 30
    depends_on: 'windows-2020-fixture'
    agents:
      queue: win-general-1
    env:
      UNITY_VERSION: "2020.3.32f1"
    commands:
      - cd features/fixtures/maze_runner/build
      - unzip Windows-$UNITY_VERSION%.zip
      - cd ../../../..
      - bundle install
      - bundle exec maze-runner --app=features/fixtures/maze_runner/build/Windows/Mazerunner.exe --os=windows features/desktop
    artifact_paths:
      - maze_output/**/*


