agents:
  queue: macos-12-arm-unity

steps:

  #
  # Build notifier.  We run tests for all Unity versions with the 2018 artifacts, as that is what we ship.
  #
  - label: Build released notifier artifact
    timeout_in_minutes: 30
    key: 'build-artifacts'
    env:
      DEVELOPER_DIR: "/Applications/Xcode13.4.app"
      UNITY_VERSION: "2018.4.36f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: Ensure notifier builds on Windows (for development)
    timeout_in_minutes: 30
    agents:
      queue: windows-unity-wsl
    env:
      UNITY_VERSION: "2018.4.36f1"
      WSLENV: UNITY_VERSION
    command:
      - /mnt/c/Windows/System32/cmd.exe /c  .\\scripts\\ci-build-windows-plugin.bat
    plugins:
      artifacts#v1.5.0:
        upload:
          - from: Bugsnag.unitypackage
            to: Bugsnag_WindowsBuilt.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  # Build macOS and WebGL test fixtures
  #
  - label: Matrix on a group
    depends_on: 'build-artifacts'
    matrix:
      - 2018.4.36f1
      - 2019.4.35f1
    group:
    steps:
      - label: Build
        timeout_in_minutes: 30
        key: 'build'
        env:
          DEVELOPER_DIR: "/Applications/Xcode13.4.app"
          UNITY_VERSION: "2018.4.36f1"
          # Python2 needed for WebGL to build
          EMSDK_PYTHON: "/Library/Frameworks/Python.framework/Versions/2.7/bin/python"
        plugins:
          artifacts#v1.5.0:
            download:
              - Bugsnag.unitypackage
        commands:
          - scripts/ci-build-macos-packages.sh
        artifact_paths:
          - unity.log
          - features/fixtures/maze_runner/build/MacOS-2018.4.36f1.zip

      - label: Run tests
        timeout_in_minutes: 60
        depends_on: 'build'
        agents:
          queue: macos-12-arm-unity
        env:
          UNITY_VERSION: "2018.4.36f1"
        plugins:
          artifacts#v1.5.0:
            download:
              - features/fixtures/maze_runner/build/MacOS-2018.4.36f1.zip
        commands:
          - scripts/ci-run-macos-tests-csharp.sh

