agents:
  queue: macos-12-arm-unity

steps:
  #
  # Build notifier.  We run tests for all Unity versions with the 2018 artifacts, as that is what we ship.
  #
  - label: Build released notifier artifact
    timeout_in_minutes: 30
    key: "build-artifacts"
    env:
      DEVELOPER_DIR: "/Applications/Xcode14.0.app"
      UNITY_VERSION: "2018.4.36f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
    artifact_paths:
      - Bugsnag.unitypackage
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  # Build Android test fixtures
  - label: ":android: Build Android test fixture for Unity 2020"
    timeout_in_minutes: 30
    key: "build-android-fixture-2020"
    depends_on: "build-artifacts"
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - Bugsnag.unitypackage
        upload:
          - features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk
          - features/fixtures/build_android_apk.log
    commands:
      - rake test:android:build
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  #
  # Run Android tests
  #
  - label: ":bitbar: :android: Run Android e2e tests for Unity 2020"
    timeout_in_minutes: 60
    depends_on: "build-android-fixture-2020"
    agents:
      queue: opensource
    env:
      UNITY_VERSION: "2020.3.48f1"
    plugins:
      artifacts#v1.5.0:
        download:
          - "features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk"
        upload:
          - "maze_output/**/*"
          - "maze_output/metrics.csv"
      docker-compose#v4.7.0:
        pull: maze-runner-bitbar
        run: maze-runner-bitbar
        service-ports: true
        command:
          - "features/csharp"
          - "features/android"
          - "--app=features/fixtures/maze_runner/mazerunner_2020.3.48f1.apk"
          - "--farm=bb"
          - "--device=ANDROID_9|ANDROID_10|ANDROID_11|ANDROID_12|ANDROID_13"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
    concurrency: 25
    concurrency_group: "bitbar"
    concurrency_method: eager

  #
  # Conditionally trigger full pipeline
  #
  - label: "Conditionally trigger full set of tests"
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
